service: go-service

provider:
  name: aws
  runtime: go1.x
  region: us-east-1

functions:
  hello:
    handler: bin/hello
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: hello
          method: get

package:
  include:
    - bin/**
